### ISSUE TITLE
The archive for imagenet_v2 has changed (again)

### ISSUE THREAD

**Issue by pkubik** [tensorflow/datasets#2888]
An error from  #2461 reappeared:

```
ds = tfds.load('imagenet_v2')
```

It seems like the file hosted at https://s3-us-west-2.amazonaws.com/imagenetv2public/imagenetv2-matched-frequency.tar.gz has changed and the checksum doesn't match.

What's even worse the directory layout has been changed - I've extracted the archive manually but it the code still failed.

The previous convention was <class_id>/<filename> where <class_id> is one of [0, 1000) classes. Now it seems like they retreated to the original ImageNet convention with <synset_id>/<filename>. I guess the original imagenet2012 code from tfds can be reused to make it work now.

Sample files for reference:
```
TAR_GZ.s3-us-west-2_image_image-match-frequc56VsOLVttUFrJ7Ka21jcV9uodSP_TSQV-yxfB4t3_U.tar.gz/imagenetv2-matched-frequency-format-val/n02865351/6.jpeg
TAR_GZ.s3-us-west-2_image_image-match-frequc56VsOLVttUFrJ7Ka21jcV9uodSP_TSQV-yxfB4t3_U.tar.gz/imagenetv2-matched-frequency-format-val/n02865351/13.jpeg
TAR_GZ.s3-us-west-2_image_image-match-frequc56VsOLVttUFrJ7Ka21jcV9uodSP_TSQV-yxfB4t3_U.tar.gz/imagenetv2-matched-frequency-format-val/n02865351/2.jpeg
...
```

Besides it's rather unfortunate that the code rely on an external URL that already changed it content (at least) two times. Is there a chance that Google could host a more stable version, i.e. with versioning and no unexpected overwrites.

**Comment by vijayphoenix** [comment]
Hi @pkubik,
This should be fixed soon.

**Comment by ajbrock** [comment]
Hi @vijayphoenix,
This error is not fixed for me, just running
```
import tensorflow_datasets as tfds
ds = tfds.load('imagenet_v2')
```
yields the  checksum error
```
NonMatchingChecksumError: Artifact https://s3-us-west-2.amazonaws.com/imagenetv2public/imagenetv2-matched-frequency.tar.gz, downloaded to /root/tensorflow_datasets/downloads/s3-us-west-2_image_image-match-frequc56VsOLVttUFrJ7Ka21jcV9uodSP_TSQV-yxfB4t3_U.tar.gz.tmp.d801552520744b8488c6dc8a171c345c/imagenetv2-matched-frequency.tar.gz, has wrong checksum. This might indicate:.....
```

Is there a way to fix this? Thanks.

**Comment by Conchylicultor** [comment]
@ajbrock For your logs, it seems you're using an old TFDS version. You can fix the issue by installing `tfds-nightly`.

**Comment by ajbrock** [comment]
I'm running this on a public colab, is there a way to get the version colab uses updated?

**Comment by vijayphoenix** [comment]
@ajbrock Run the following command
`pip install tfds-nightly`

**Comment by ajbrock** [comment]
ah got it, just using colab's inbuilt pip. Thanks!
