### ISSUE TITLE
Outdated caltech101 URL

### ISSUE THREAD

**Issue by CrimsonRadiator** [tensorflow/datasets#2925]
**Short description**
TFDS uses outdated caltech101 url and fails to download the dataset.

**Environment information**
* Operating System: Ubuntu 18.04.5 LTS
* Python version: 3.6.9
* `tensorflow-datasets`/`tfds-nightly` version: tfds-nightly==4.2.0.dev202101080107
* `tensorflow`/`tf-nightly` version: tensorflow==2.4.0

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? yes

**Reproduction instructions**

```
import tensorflow_datasets as tfds
tfds.load('caltech101',split='test')
```

**Link to logs**

>NonMatchingChecksumError: Artifact http://www.vision.caltech.edu/Image_Datasets/Caltech101/101_ObjectCategories.tar.gz, downloaded to /root/tensorflow_datasets/downloads/visi.calt.edu_Imag_Data_Calt_101_ObjeCbXKudn0uTOxGnJlXTlpRrWjwNzJ-raVgKRm6R5O0eY.tar.gz.tmp.98a65209f7b74c5c94336fb375ab45c6/view, has wrong checksum. Expected: UrlInfo(size=125.64 MiB, checksum='af6ece2f339791ca20f855943d8b55dd60892c0a25105fcd631ee3d6430f9926', filename='view'). Got: UrlInfo(size=69.33 KiB, checksum='21b5437a74d742ae09fb9f09f59446e6dcd0371a4e9513ac9c84ff632de5a4f0', filename='view').To debug, see: https://www.tensorflow.org/datasets/overview#fixing_nonmatchingchecksumerror

**Expected behavior**
The dataset should download successfully.

**Additional context**
I've already fixed it and hopefully will add PR in a few minutes.

**Comment by NikhilBartwal** [comment]
Thank you for pointing it out @CrimsonRadiator. Please feel free to send a PR for the same!

**Comment by vijayphoenix** [comment]
Fixed by #2927

**Comment by hamed-ahangari** [comment]
Sorry to bring it up again, but I still have a problem with loading Caltech101 using `tfds`.

I'm trying to run this piece of code:
`
dataset_name = "caltech101"
caltech101, ds_info = tfds.load(
    dataset_name, split="train", with_info=True, as_supervised=True
)
`
But an exception would happen like this:
`
NonMatchingChecksumError: Artifact http://www.vision.caltech.edu/Image_Datasets/Caltech101/101_ObjectCategories.tar.gz, downloaded to /root/tensorflow_datasets/downloads/visi.calt.edu_Imag_Data_Calt_101_ObjeCbXKudn0uTOxGnJlXTlpRrWjwNzJ-raVgKRm6R5O0eY.tar.gz.tmp.540c6f625c2348199db4787208439ce9/view, has wrong checksum. Expected: UrlInfo(size=125.64 MiB, checksum='af6ece2f339791ca20f855943d8b55dd60892c0a25105fcd631ee3d6430f9926', filename='view'). Got: UrlInfo(size=69.68 KiB, checksum='6d7781c5c69cd7dbb9f4d2bf5d64c7b18e79538a6bc19dcb490bf9ad7291290e', filename='view').To debug, see: https://www.tensorflow.org/datasets/overview#fixing_nonmatchingchecksumerror
`

Any help with this would be appreciated.
